version: "2"
linters:
  # Default set of linters.
  # The value can be: `standard`, `all`, `none`, or `fast`.
  # Default: standard
  default: standard
  enable:
    - zerologlint
    - testifylint
    - paralleltest
    - copyloopvar
    - godox
  settings:
    godox:
      keywords:
      - "DEBUG"
      - "TODO"
